// Kuraterte opplevelser. Pris i NOK.
// bookingUrl: legg inn din affiliate-/booking-lenke (Klook, GetYourGuide, Viator
// eller egen kontrakt). Er den tom, åpnes forespørselsskjemaet i stedet.
export const experiences = [
  {
    id: 'elephant-chiangmai',
    title: 'Etisk elefantreservat',
    place: 'Chiang Mai',
    category: 'Natur & dyr',
    emoji: '🐘',
    gradient: 'linear-gradient(135deg, #0f6b5c, #1f9e6f)',
    duration: 'Heldag',
    rating: 4.9,
    reviews: 1284,
    priceNOK: 890,
    oldPriceNOK: 1090,
    blurb:
      'Mat og bad elefantene i et sertifisert reservat uten ridning. Henting på hotellet og lunsj inkludert.',
    tags: ['Familievennlig', 'Etisk', 'Henting inkl.'],
    bestseller: true,
    bookingUrl: '',
  },
  {
    id: 'phiphi-maya',
    title: 'Phi Phi & Maya Bay speedbåt',
    place: 'Phuket',
    category: 'Øyer & strender',
    emoji: '🏝️',
    gradient: 'linear-gradient(135deg, #1591b7, #46c6d6)',
    duration: 'Heldag',
    rating: 4.8,
    reviews: 2041,
    priceNOK: 1190,
    oldPriceNOK: 1390,
    blurb:
      'Snorkling, skjulte laguner og lunsj på stranden. Besøk de mest ikoniske øyene i Andamanhavet.',
    tags: ['Snorkling', 'Lunsj inkl.', 'Bestselger'],
    bestseller: true,
    bookingUrl: '',
  },
  {
    id: 'cooking-bangkok',
    title: 'Thai matlagingskurs + marked',
    place: 'Bangkok',
    category: 'Mat & kultur',
    emoji: '🍜',
    gradient: 'linear-gradient(135deg, #e8502f, #ff8f4a)',
    duration: '4 timer',
    rating: 4.9,
    reviews: 876,
    priceNOK: 640,
    oldPriceNOK: null,
    blurb:
      'Handle på et lokalt marked og lag fem klassiske retter med en lokal kokk. Oppskrifter på norsk.',
    tags: ['Liten gruppe', 'Vegetar-mulig'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'temple-bangkok',
    title: 'Tempeltur: Wat Arun & Storpalasset',
    place: 'Bangkok',
    category: 'Mat & kultur',
    emoji: '🛕',
    gradient: 'linear-gradient(135deg, #b8860b, #f2b705)',
    duration: 'Halvdag',
    rating: 4.7,
    reviews: 1533,
    priceNOK: 550,
    oldPriceNOK: 650,
    blurb:
      'Norsktalende guide tar deg gjennom byens vakreste templer, med historien bak hvert sted.',
    tags: ['Norsk guide', 'Inngang inkl.'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'jamesbond-phuket',
    title: 'James Bond Island & kajakk',
    place: 'Phang Nga',
    category: 'Øyer & strender',
    emoji: '⛰️',
    gradient: 'linear-gradient(135deg, #12776a, #3fb0a0)',
    duration: 'Heldag',
    rating: 4.8,
    reviews: 967,
    priceNOK: 980,
    oldPriceNOK: null,
    blurb:
      'Padle mellom dramatiske kalksteinsformasjoner i Phang Nga-bukten. Buffélunsj om bord.',
    tags: ['Kajakk', 'Lunsj inkl.'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'muaythai-bangkok',
    title: 'Muay Thai — Rajadamnern Stadium',
    place: 'Bangkok',
    category: 'Adrenalin',
    emoji: '🥊',
    gradient: 'linear-gradient(135deg, #7a1f2b, #e8502f)',
    duration: 'Kveld',
    rating: 4.6,
    reviews: 612,
    priceNOK: 490,
    oldPriceNOK: null,
    blurb:
      'VIP-billetter til ekte Muay Thai på Thailands mest legendariske arena. Ringside-plasser.',
    tags: ['VIP', 'Kveldsaktivitet'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'safariworld-bangkok',
    title: 'Safari World & Marine Park',
    place: 'Bangkok',
    category: 'Familie',
    emoji: '🦁',
    gradient: 'linear-gradient(135deg, #2e7d32, #8bc34a)',
    duration: 'Heldag',
    rating: 4.5,
    reviews: 1120,
    priceNOK: 720,
    oldPriceNOK: 860,
    blurb:
      'Kjør safari blant løver og giraffer, og se delfin- og sjøløveshow. Perfekt for barnefamilier.',
    tags: ['Familievennlig', 'Show inkl.'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'zipline-chiangmai',
    title: 'Zipline jungel-eventyr',
    place: 'Chiang Mai',
    category: 'Adrenalin',
    emoji: '🌴',
    gradient: 'linear-gradient(135deg, #0f6b5c, #6fcf67)',
    duration: 'Halvdag',
    rating: 4.8,
    reviews: 734,
    priceNOK: 850,
    oldPriceNOK: null,
    blurb:
      'Fly gjennom regnskogen på over 30 plattformer. Sertifiserte guider og alt utstyr inkludert.',
    tags: ['Adrenalin', 'Henting inkl.'],
    bestseller: false,
    bookingUrl: '',
  },
  {
    id: 'floating-market',
    title: 'Flytende marked + jernbanemarked',
    place: 'Ratchaburi',
    category: 'Mat & kultur',
    emoji: '🛶',
    gradient: 'linear-gradient(135deg, #1591b7, #6fcf67)',
    duration: 'Heldag',
    rating: 4.7,
    reviews: 903,
    priceNOK: 610,
    oldPriceNOK: 720,
    blurb:
      'Opplev Damnoen Saduak fra langbåt og det berømte markedet på togskinnene. Fotoparadis.',
    tags: ['Kultur', 'Henting inkl.'],
    bestseller: false,
    bookingUrl: '',
  },
];

export const categories = [
  'Alle',
  'Natur & dyr',
  'Øyer & strender',
  'Mat & kultur',
  'Adrenalin',
  'Familie',
];

export const destinations = [
  { name: 'Bangkok', emoji: '🛕', count: 24 },
  { name: 'Phuket', emoji: '🏝️', count: 19 },
  { name: 'Chiang Mai', emoji: '🐘', count: 16 },
  { name: 'Krabi', emoji: '🚤', count: 12 },
  { name: 'Koh Samui', emoji: '🌴', count: 11 },
  { name: 'Pattaya', emoji: '🎢', count: 9 },
];

// PLASSHOLDER-anmeldelser — bytt ut med ekte kundeanmeldelser før lansering.
export const testimonials = [
  {
    name: 'Kari',
    city: 'Oslo',
    text: 'Elefantparken var årets høydepunkt for hele familien. Alt var ordnet på forhånd, og vi fikk svar på norsk innen minutter.',
    exp: 'Etisk elefantreservat',
  },
  {
    name: 'Ola',
    city: 'Bergen',
    text: 'Matkurset i Bangkok var utrolig gøy. Digg å slippe å tolke engelske oppskrifter — alt kom på norsk.',
    exp: 'Thai matlagingskurs',
  },
  {
    name: 'Ingrid',
    city: 'Trondheim',
    text: 'Booket Phi Phi-turen kvelden før. Superenkelt, betalte i kroner, og guiden ventet på oss på hotellet.',
    exp: 'Phi Phi & Maya Bay',
  },
];
